language: php

php:
  - 5.5
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 7.0
  fast_finish: true

before_script: composer install --no-interaction --prefer-source --dev

script:
  - phpunit --configuration phpunit.xml --coverage-clover clover.xml

after_script:
  - bash <(curl -s https://codecov.io/bash)
